FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /sln

COPY ./*.sln ./

COPY src/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p src/${file%.*}/ && mv $file src/${file%.*}/; done

COPY test/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p test/${file%.*}/ && mv $file test/${file%.*}/; done

RUN dotnet test

RUN dotnet restore /sln/src/NJ.Web.WebApi
COPY . .
WORKDIR /sln/src/NJ.Web.WebApi
RUN dotnet build --configuration Release --output /app

FROM build AS publish
RUN dotnet publish --configuration Release --output /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "./NJ.Web.WebApi.dll"]